title: Product Tax Rate
description: >-
  This represents the association between a tax rate and a product to indicate
  that the product is taxed in a way different than the default.
type: object
required:
  - created_at
  - metadata
  - product_id
  - rate_id
  - updated_at
properties:
  product_id:
    description: The ID of the Product
    type: string
    example: prod_01G1G5V2MBA328390B5AXJ610F
  product:
    description: The details of the product.
    x-expandable: product
    nullable: true
    $ref: ./Product.yaml
  rate_id:
    description: The ID of the Tax Rate
    type: string
    example: txr_01G8XDBAWKBHHJRKH0AV02KXBR
  tax_rate:
    description: The details of the tax rate.
    x-expandable: tax_rate
    nullable: true
    $ref: ./TaxRate.yaml
  created_at:
    description: The date with timezone at which the resource was created.
    type: string
    format: date-time
  updated_at:
    description: The date with timezone at which the resource was updated.
    type: string
    format: date-time
  metadata:
    description: An optional key-value map with additional details
    nullable: true
    type: object
    example:
      car: white
    externalDocs:
      description: Learn about the metadata attribute, and how to delete and update it.
      url: >-
        https://docs.medusajs.com/development/entities/overview#metadata-attribute
